networks:
  vearch_network_cluster:
    driver: bridge
    name: vearch_network_cluster
    ipam:
      config:
        - subnet: 172.16.238.0/24

services:
  standalone:
    container_name: vearch-standalone
    image: vearch/vearch:latest
    privileged: true
    networks:
      - vearch_network_cluster
    ports:
      - "8817:8817"
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config.toml:/vearch/config.toml
    command: all
    profiles:
      - standalone

  master1:
    container_name: vearch-master1
    image: vearch/vearch:latest
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.10
    ports:
      - "8817:8817"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - cluster
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:8817 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  master2:
    container_name: vearch-master2
    image: vearch/vearch:latest
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.11
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - cluster
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:8817 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  master3:
    container_name: vearch-master3
    image: vearch/vearch:latest
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.12
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - cluster
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:8817 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  router1:
    container_name: vearch-router1
    image: vearch/vearch:latest
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.13
    ports:
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: router
    profiles:
      - cluster
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9001 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  router2:
    container_name: vearch-router2
    image: vearch/vearch:latest
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.14
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: router
    profiles:
      - cluster
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9001 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  ps1:
    container_name: vearch-ps1
    image: vearch/vearch:latest
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.15
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - cluster
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy

  ps2:
    container_name: vearch-ps2
    image: vearch/vearch:latest
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.16
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - cluster
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy

  ps3:
    container_name: vearch-ps3
    image: vearch/vearch:latest
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.17
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - cluster
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy

  ps4:
    container_name: vearch-ps4
    image: vearch/vearch:latest
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.18
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - manual_startif
