networks:
  vearch_network_cluster:
    driver: bridge
    name: vearch_network_cluster
    ipam:
      config:
        - subnet: 172.16.238.0/24

services:
  standalone:
    container_name: vearch-standalone
    image: vearch/vearch:latest
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      - vearch_network_cluster
    ports:
      - "8817:8817"
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config.toml:/vearch/config.toml
    command: all
    profiles:
      - standalone

  master1:
    container_name: vearch-master1
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.10
      - VEARCH_HOST_RACK=rack1
      - VEARCH_HOST_ZONE=zone1
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.10
    ports:
      - "8817:8817"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - cluster
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:8817 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  master2:
    container_name: vearch-master2
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.11
      - VEARCH_HOST_RACK=rack2
      - VEARCH_HOST_ZONE=zone2
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.11
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - cluster
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:8817 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  master3:
    container_name: vearch-master3
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.12
      - VEARCH_HOST_RACK=rack3
      - VEARCH_HOST_ZONE=zone3
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.12
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - cluster
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:8817 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  master4:
    container_name: vearch-master4
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.13
      - VEARCH_HOST_RACK=rack4
      - VEARCH_HOST_ZONE=zone4
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.13
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: master
    profiles:
      - manual_startif

  router1:
    container_name: vearch-router1
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.14
      - VEARCH_HOST_RACK=rack5
      - VEARCH_HOST_ZONE=zone5
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.14
    ports:
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: router
    profiles:
      - cluster
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9001 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  router2:
    container_name: vearch-router2
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.15
      - VEARCH_HOST_RACK=rack6
      - VEARCH_HOST_ZONE=zone6
    platform: ${TARGET_PLATFORM}
    privileged: true
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.15
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: router
    profiles:
      - cluster
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9001 -u root:secret"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  ps1:
    container_name: vearch-ps1
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.16
      - VEARCH_HOST_RACK=rack7
      - VEARCH_HOST_ZONE=zone7
    platform: ${TARGET_PLATFORM}
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.16
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - cluster
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy

  ps2:
    container_name: vearch-ps2
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.17
      - VEARCH_HOST_RACK=rack8
      - VEARCH_HOST_ZONE=zone8
    platform: ${TARGET_PLATFORM}
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.17
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - cluster
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy

  ps3:
    container_name: vearch-ps3
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.18
      - VEARCH_HOST_RACK=rack9
      - VEARCH_HOST_ZONE=zone9
    platform: ${TARGET_PLATFORM}
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.18
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - cluster
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy

  ps4:
    container_name: vearch-ps4
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.19
      - VEARCH_HOST_RACK=rack10
      - VEARCH_HOST_ZONE=zone10
    platform: ${TARGET_PLATFORM}
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.19
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - manual_startif

  ps5:
    container_name: vearch-ps5
    image: vearch/vearch:latest
    environment:
      - VEARCH_HOST_IP=172.20.238.19
      - VEARCH_HOST_RACK=rack10
      - VEARCH_HOST_ZONE=zone10
    platform: ${TARGET_PLATFORM}
    networks:
      vearch_network_cluster:
        ipv4_address: 172.16.238.20
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config_cluster.toml:/vearch/config.toml
    command: ps
    profiles:
      - manual_startif
