[global]
    # The name will validate join cluster by the same name
    name = "cbdb"
    # Specify which resources to use to create space
    resource_name = "default"
    # Your data save to disk path. If you are in a production environment, you'd better set absolute paths
    data = ["datas/","datas1/"]
    # Log path. If you are in a production environment, you'd better set absolute paths
    log = "logs/"
    # Default log type for any model
    level = "debug"
    # Master <-> ps <-> router will use this key to send or receive data
    signkey = "secret"
    # Skip auth for master and router
    skip_auth = true
    # Tell Vearch whether it should manage its own instance of etcd or not
    self_manage_etcd = false
    # Automatically remove the failed node and recover when new nodes join
    auto_recover_ps = false
    # Support access etcd basic auth, depends on self_manage_etcd = true
    support_etcd_auth = false
    # Ensure leader-follow raft data synchronization is consistent
    raft_consistent = false

# self_manage_etcd = true means manage etcd by yourself, need to provide additional configuration
[etcd]
    # etcd server IP or domain
    address = ["127.0.0.1"]
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2379
    # Provide username and password if you turn on auth
    user_name = "root"
    password = ""

# If you are master you'd better set all config for router and ps, and router and ps use default config, it is so cool
[[masters]]
    # Name machine name for cluster
    name = "m1"
    # IP or domain
    address = "127.0.0.1"
    # API port for HTTP server
    api_port = 8817
    # Port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma-separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs need to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs need to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370
    # Init cluster state
    cluster_state = "new"
    pprof_port = 6062
    # Monitor
    monitor_port = 8818

[router]
    # Port for server
    port = 9001
    # rpc_port = 9002
    pprof_port = 6061
    plugin_path = "plugin"

[ps]
    # Port for server
    rpc_port = 8081
    ps_heartbeat_timeout = 5 # seconds
    # Raft config begin
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 200 # ms
    raft_retain_logs = 20000000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1
    raft_truncate_count = 500000
    # When behind leader this value, will stop the server for search
    raft_diff_count = 10000
    # Engine config
    pprof_port = 6060
    # If set true, this ps only use in db meta config
    private = false
    # Seconds
    flush_time_interval = 600
    flush_count_threshold = 200000
