name: CI_cluster

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  cluster-build-and-test:
    strategy:
      matrix:
        include:
          - platform: amd64
            runs-on: ubuntu-latest
            docker-arch: ""
          - platform: arm64
            runs-on: ubuntu-latest
            docker-arch: "--platform linux/arm64"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.platform == 'arm64'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: matrix.platform == 'arm64'
      uses: docker/setup-buildx-action@v3

    - name: Compile and Build
      run: |
        cd cloud
        docker run --name vearch-dev ${{ matrix.docker-arch }} --privileged -i -v $(dirname "$PWD"):/vearch vearch/vearch-dev-env:latest /vearch/cloud/compile/compile.sh
        cp -r ../build/bin compile/; cp -r ../build/lib compile/
        docker build ${{ matrix.docker-arch }} -t vearch/vearch:latest .
        cp ../config/config_cluster.toml .
        sed -i 's/resource_limit_rate = 0.85/resource_limit_rate = 0.98/' config_cluster.toml
        if [ "${{ matrix.docker-arch }}" == "--platform linux/arm64" ]; then
          echo "    rpc_timeout = 500" >> config_cluster.toml
        fi
        cat config_cluster.toml
        docker rm vearch-dev
        docker rmi vearch/vearch-dev-env:latest

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "cloud/docker-compose.yml"
        up-flags: "-d"
        compose-flags: "--profile cluster"

    - name: Create Minio bucket
      run: |
        mkdir test/oss_data
        docker run -d --name minio -p 10000:9000 --network vearch_network_cluster minio/minio server test/oss_data
        wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc alias set myminio http://127.0.0.1:10000 minioadmin minioadmin
        ./mc mb myminio/test

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Install Dependency
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requests pytest wheel pandas numpy minio
        cd sdk/python
        python setup.py bdist_wheel
        pip install dist/pyvearch*

    - name: Run Python tests
      run: |
        cd test
        pytest test_vearch.py -x --log-cli-level=INFO
        pytest test_document_* -k "not test_vearch_document_upsert_benchmark" -x --log-cli-level=INFO
        pytest test_module_* -x --log-cli-level=INFO

    - name: Test Go SDK
      run: |
        cd sdk/go/test
        go test -v

    - name: Test Python SDK
      run: |
        cd sdk/python/test
        pytest -x --log-cli-level=INFO

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Run tests for master down
      run: |
        cd cloud
        docker-compose stop master1
        cd ../test
        pytest test_vearch.py -x --log-cli-level=INFO
        cd ../cloud
        docker-compose start master1

    - name: Run tests for restart ps
      run: |
        cd test
        pytest test_cluster_ps.py -k "TestClusterPartitionServerAdd" -x --log-cli-level=INFO
        cd ../cloud
        docker-compose stop ps1
        sleep 30
        docker-compose start ps1
        cd ../test
        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerRecover" --log-cli-level=INFO
        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerCheckSpace" --log-cli-level=INFO
        pytest test_cluster_ps.py -x -k "TestClusterPartitionServerDestroy" --log-cli-level=INFO
        pytest test_cluster_ps.py -k "TestClusterPartitionChange" --log-cli-level=INFO
