name: CI Cluster

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  cluster-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
            docker-arch: ""
          - platform: linux/arm64
            runs-on: ubuntu-latest
            docker-arch: "--platform linux/arm64"
    runs-on: ${{ matrix.runs-on }}

    env:
      TARGET_PLATFORM: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Set cluster env
      uses: ./.github/actions/set_cluster_env
      with:
        build-type: github

    - name: Create Minio bucket
      continue-on-error: true
      run: |
        mkdir test/oss_data
        docker run -d --name minio -p 10000:9000 --network vearch_network_cluster minio/minio server test/oss_data
        wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        retry=0
        max_retries=10
        until ./mc alias set myminio http://127.0.0.1:10000 minioadmin minioadmin; do
          retry=$((retry+1))
          if [ $retry -gt $max_retries ]; then
            echo "Failed to set minio alias after $max_retries attempts."
            exit 1
          fi
          echo "Retry $retry/$max_retries: Failed to set minio alias. Retrying in 5 seconds..."
          sleep 5
        done
        ./mc mb myminio/test

    - name: Run Python tests
      run: |
        cd test
        pytest test_vearch.py -x --log-cli-level=INFO
        pytest test_document_* -k "not test_vearch_document_upsert_benchmark" -x --log-cli-level=INFO
        pytest test_module_* -x --log-cli-level=INFO

    - name: Test Go SDK
      run: |
        cd sdk/go/test
        go test -v

    - name: Build python sdk
      run: |
        cd sdk/python
        python setup.py bdist_wheel
        pip install dist/pyvearch*

    - name: Test Python SDK
      run: |
        cd sdk/python/test
        pytest -x --log-cli-level=INFO
