name: Python SDK CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: compile
        run: |
          pwd
          ls -l
          cd cloud
          docker run --privileged -i -v $(dirname "$PWD"):/vearch vearch/vearch-dev-env:latest /vearch/cloud/compile/compile.sh
          cp -r ../build/bin compile/; cp -r ../build/lib compile/
          docker build -t vearch/vearch:latest .
  
      - name: gen config
        run: |
          cd cloud
          cp ../config/config.toml .
      - name: run docker
        run: |
          cd cloud
          nohup docker run -p 8817:8817 -p 9001:9001 -v $PWD/config.toml:/vearch/config.toml vearch/vearch:latest all &
      - name: sleep
        run: sleep 30s
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install requests pytest wheel pandas
          cd sdk/python
          python setup.py bdist_wheel
          pip install dist/pyvearch*
      - name: python sdk test
        run: |
          cd sdk/python/test
          pytest
